export {default as DarkLogo} from './dark_logo'
export {default as LightLogo} from './light_logo'
export {default as UzbLogo} from './uzb'
export {default as RusLogo} from './rus'
export {default as EngLogo} from './eng'
export {default as AnnouncementIcons} from './announcement'
export {default as CodingIcons} from './coding';
export {default as DesignIcons} from './design';
export {default as LaptopIcons} from './laptop';
export {default as PersonIcons} from './person';
export {default as PrintIcons} from './print';
export {default as PersontIcons} from './persont';
export {default as OnlineCourseIcons} from './online-course'
export {default as OnlineLearningIcons} from './online-learning'
export {default as RightLineIcons} from './right-line'
export {default as OnlineStudentIcons} from './online-student'